apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maximo-hail-pz-app-pipeline-run-
spec:
  params:
    - name: source-repo
      value: https://github.com/poonamzham/maximo-hail
    - name: app-name
      value: maximo-hail-pz-app
    - name: image-repo
      value: quay.io/poonamzham0/maximo_demo
  serviceAccountName: build-bot
  pipelineRef:
    name: maximo-hail-pz-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
