apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maximo-hail-app-pipeline-run-
spec:
  params:
    - name: source-repo
      value: https://github.com/sherryyyu/maximo-hail
    - name: app-name
      value: maximo-hail-app
    - name: image-repo
      value: quay.io/sherryyu/maximo-hail
  serviceAccountName: build-bot
  pipelineRef:
    name: maximo-hail-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
