apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  params:
    - name: source-repo
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: maximo-hail-app-pipeline-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: maximo-hail-pipeline
        params:
          - name: source-repo
            value: $(tt.params.source-repo)
          - name: image-repo
            value: quay.io/sherryyu/maximo-hail
          - name: app-name
            value: maximo-hail-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger
spec:
  params:
    - name: source-repo
      value: $(body.repository.url)
    - name: commit
      value: $(body.head_commit.id)
