apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: maximo-hail-app
  app.kubernetes.io/instance: maximo-hail-app-instance
  app.kubernetes.io/name: maximo-hail-app
