apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: maximo-hail-pz-app
  app.kubernetes.io/instance: maximo-hail-pz-app-instance
  app.kubernetes.io/name: maximo-hail-pz-app
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/poonamzham0/maximo_demo:{IMAGE_SHA}
