apiVersion: v1
kind: Service
metadata:
  labels:
    app: maximo-hail-pz-app
    app.kubernetes.io/instance: maximo-hail-pz-app-instance
    app.kubernetes.io/name: maximo-hail-pz-app
  name: maximo-hail-pz-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: maximo-hail-pz-app-instance
    app.kubernetes.io/name: maximo-hail-pz-app
  sessionAffinity: None
  type: ClusterIP
